### ISSUE TITLE
Cannot run deploy staging with current zipped shopware 5.5.4

### ISSUE THREAD

**Issue by Forestsoft-de** [kellerkinderDE/deployer#3]
On kellerkinder:vendors task breaks with:

>  Warning: Ambiguous class resolution, "Doctrine\ORM\Persisters\Entity\BasicEntityPersister" was found in both "$baseDir . '/engine/Library/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php" and "/www/casamia.local/releases/2/sr
  c/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php", the first will be used.
  Warning: Ambiguous class resolution, "Doctrine\Common\Proxy\AbstractProxyFactory" was found in both "$baseDir . '/engine/Library/Doctrine/Common/Proxy/AbstractProxyFactory.php" and "/www/casamia.local/releases/2/src/vendor/doctrine/
  common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php", the first will be used.
      Skipped installation of bin bin/doctrine-dbal for package doctrine/dbal: file not found in package
      Skipped installation of bin bin/doctrine for package doctrine/orm: file not found in package
      Skipped installation of bin bin/doctrine.php for package doctrine/orm: file not found in package
  > ./build/composer-post-update-cmd.sh
  sh: 1: ./build/composer-post-update-cmd.sh: not found
  Script ./build/composer-post-update-cmd.sh handling the post-update-cmd event returned with error code 127

**Comment by Forestsoft-de** [comment]
i think there is a problem mixing shopware download package and composer actions in showare root path.

**Comment by kleinmann** [comment]
Are you using the GitHub repository of Shopware directly instead of a published release? This configuration assumes you're using a valid distribution of Shopware.

**Comment by kleinmann** [comment]
@Forestsoft-de Can you confirm that the issue is fixed after applying #4?

**Comment by kleinmann** [comment]
Closed due to lack of response. If your issue remains, feel free to open another issue :-)
