### ISSUE TITLE
Shouldn't deploy:update_code clone repo to shopware_public_dir?

### ISSUE THREAD

**Issue by rawdlite** [kellerkinderDE/deployer#9]
Hi,

Thanks a lot for sharing this code.
At the moment i am going through the tasks of deploy:staging trying to figure them out and getting them to run.
Now when i do deploy:update_code my code gets cloned to {{release_path}}.
- /var/www/mobl/releases/2/custom/plugins/
- /var/www/mobl/releases/2/themes/Frontend/Mobl
etc.

When i do kellerkinder:shopware:configure, kellerkinder:shopware:plugins expects the plugin code to be in {{shopware_public_path}} 
- /var/www/mobl/releases/2/web/custom/plugins/

defined by: set('shopware_public_dir', 'web');
Am i doing something wrong here?
When copying the plugins from release_path to shopware_public_path it works.
So this could be done by overwriting deploy:update_code to use shopware_public_path instead of release_path.
On the other hand i do not really understand why there is a shopware_public_dir at all.
So i am probably missing something entirely.

TIA
tom

**Comment by kleinmann** [comment]
Hi @rawdlite, we're using a specific repository structure where "everything regarding Shopware" is located in a subdirectory `web` (as set in `shopware_public_dir`). This is done so all project-related stuff like the deployer files can be located in the project root, without being exposed via the web server.
I hope this clears things up for you :-)

Best regards

**Comment by rawdlite** [comment]
Ah, ok.
Thank you, that perfectly explains it.
As i have the non shopware files in another repo, i will just set shopware_public_path to release_path and it should work for me without changing much in your code.
